export const constants = {
  HEADER: 'Let’s Meet You',
  SUBHEADER: `Whew! Now that we're done with all the serious stuff, can we get to meet you?`,
  FULLNAME: 'First and Last name',
  FULLNAME_PH: 'FullName',
  EMAIL: 'Email Address',
  EMAIL_PH: 'Email',
  DOB: 'Date Of Birth',
  MTH_PH: 'Month',
  DAY_PH: 'Day',
  YR_PH: 'Year',
  GENDER: 'Gender',
  GENDER_PH: 'Select Gender',
  STATE: 'State Of Origin',
  STATE_PH: 'Select Your State Of Origin',
  TWITTER: 'Twitter Handle',
  TWITTER_PH: '@',
  PASSWORD: 'Password',
  PASSWORD_PH: 'Create your password',
  CONFIRM_PASSWORD: 'Confirm Password',
  CONFIRM_PASSWORD_PH: 'Re-enter your password',
  AD: `One last question, well almost the last one.
    How did you hear about Edustipend?`,
  AD_PH: 'Please select',
  QUOTE: '"The future depends on what you do today." - Mahatma Gandhi',
  DOB_TEXT: `We want to be able to support everyone fairly regardless of age. 
    Please select your correct date of birth as this cannot be changed after registration`,
  GENDER_TEXT: `We want to be able to support everyone fairly regardless of gender.`,
  TWITTER_TEXT: `If you're not on Twitter, please type N/A. If you're on some other social media platform, please share and indicate`,
  MONTHS_OPTION: ['JAN', 'FEB', 'MAR', 'APR', 'MAY', 'JUN', 'JUL', 'AUG', 'SEP', 'OCT', 'NOV', 'DEC'],
  GENDER_OPTION: ['Male', 'Female', 'Non-Binary'],
  REFERRAL_SOURCES: ['Facebook', 'LinkedIn', 'Instagram', 'Twitter', 'Google Search'],
  PASSWORD_MIN_LENGTH_ERR: 'A minimum of 8 characters is required',
  PASSWORD_MISMATCH_ERR: 'password mismatch'
};
